// app/layout.tsx or app/layout.js

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Import Toastify CSS

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <div className="bg-background h-screen font-montserrat relative">
          {children}
          {/* Add ToastContainer for global notifications */}
          <ToastContainer />
          <footer className="bottom-0 left-0 w-full h-44 md:h-28 bg-cover bg-no-repeat bg-[url(/wave-m.svg)] md:bg-[url(/wave.svg)]"></footer>
        </div>
      </body>
    </html>
  );
}
